apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-bjlh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-msfa-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-bjlh@sha256:53ee39b49ac44108758aa82efaabb5df0062b7b863df9f7869fe3dadc27b84f6
        name: my-python
        resources: {}
status: {}
